//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the prueba package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: prueba
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaySvcRs }
     * 
     */
    public PaySvcRs createPaySvcRs() {
        return new PaySvcRs();
    }

    /**
     * Create an instance of {@link PresSvcRs }
     * 
     */
    public PresSvcRs createPresSvcRs() {
        return new PresSvcRs();
    }

    /**
     * Create an instance of {@link PaySvcRq }
     * 
     */
    public PaySvcRq createPaySvcRq() {
        return new PaySvcRq();
    }

    /**
     * Create an instance of {@link PresSvcRq }
     * 
     */
    public PresSvcRq createPresSvcRq() {
        return new PresSvcRq();
    }

    /**
     * Create an instance of {@link Billdata }
     * 
     */
    public Billdata createBilldata() {
        return new Billdata();
    }

    /**
     * Create an instance of {@link Billdata.BillInfo }
     * 
     */
    public Billdata.BillInfo createBilldataBillInfo() {
        return new Billdata.BillInfo();
    }

    /**
     * Create an instance of {@link Billdata.BillInfo.PresAcctId }
     * 
     */
    public Billdata.BillInfo.PresAcctId createBilldataBillInfoPresAcctId() {
        return new Billdata.BillInfo.PresAcctId();
    }

    /**
     * Create an instance of {@link Amountdata }
     * 
     */
    public Amountdata createAmountdata() {
        return new Amountdata();
    }

    /**
     * Create an instance of {@link PmtData }
     * 
     */
    public PmtData createPmtData() {
        return new PmtData();
    }

    /**
     * Create an instance of {@link PmtData.RemitInfo }
     * 
     */
    public PmtData.RemitInfo createPmtDataRemitInfo() {
        return new PmtData.RemitInfo();
    }

    /**
     * Create an instance of {@link PresSvcRq.BillInqRq }
     * 
     */
    public PresSvcRq.BillInqRq createPresSvcRqBillInqRq() {
        return new PresSvcRq.BillInqRq();
    }

    /**
     * Create an instance of {@link PaySvcRq.MsgRqHdr }
     * 
     */
    public PaySvcRq.MsgRqHdr createPaySvcRqMsgRqHdr() {
        return new PaySvcRq.MsgRqHdr();
    }

    /**
     * Create an instance of {@link PaySvcRq.MsgRqHdr.PointOfServiceData }
     * 
     */
    public PaySvcRq.MsgRqHdr.PointOfServiceData createPaySvcRqMsgRqHdrPointOfServiceData() {
        return new PaySvcRq.MsgRqHdr.PointOfServiceData();
    }

    /**
     * Create an instance of {@link PaySvcRs.PmtAddRs }
     * 
     */
    public PaySvcRs.PmtAddRs createPaySvcRsPmtAddRs() {
        return new PaySvcRs.PmtAddRs();
    }

    /**
     * Create an instance of {@link PaySvcRs.PmtAddRs.PmtRec }
     * 
     */
    public PaySvcRs.PmtAddRs.PmtRec createPaySvcRsPmtAddRsPmtRec() {
        return new PaySvcRs.PmtAddRs.PmtRec();
    }

    /**
     * Create an instance of {@link PresSvcRs.BillInqRs }
     * 
     */
    public PresSvcRs.BillInqRs createPresSvcRsBillInqRs() {
        return new PresSvcRs.BillInqRs();
    }

    /**
     * Create an instance of {@link SignonRs }
     * 
     */
    public SignonRs createSignonRs() {
        return new SignonRs();
    }

    /**
     * Create an instance of {@link Wsclient }
     * 
     */
    public Wsclient createWsclient() {
        return new Wsclient();
    }

    /**
     * Create an instance of {@link SignonRq }
     * 
     */
    public SignonRq createSignonRq() {
        return new SignonRq();
    }

    /**
     * Create an instance of {@link Statusdata }
     * 
     */
    public Statusdata createStatusdata() {
        return new Statusdata();
    }

    /**
     * Create an instance of {@link Billdata.BillInfo.PresAcctId.BillerId }
     * 
     */
    public Billdata.BillInfo.PresAcctId.BillerId createBilldataBillInfoPresAcctIdBillerId() {
        return new Billdata.BillInfo.PresAcctId.BillerId();
    }

    /**
     * Create an instance of {@link Amountdata.CurAmt }
     * 
     */
    public Amountdata.CurAmt createAmountdataCurAmt() {
        return new Amountdata.CurAmt();
    }

    /**
     * Create an instance of {@link PmtData.CurAmt }
     * 
     */
    public PmtData.CurAmt createPmtDataCurAmt() {
        return new PmtData.CurAmt();
    }

    /**
     * Create an instance of {@link PmtData.DepAcctIdFrom }
     * 
     */
    public PmtData.DepAcctIdFrom createPmtDataDepAcctIdFrom() {
        return new PmtData.DepAcctIdFrom();
    }

    /**
     * Create an instance of {@link PmtData.CurAmt }
     * 
     */
    public PmtData.CurAmt createPmtDataRemitInfoCurAmt() {
        return new PmtData.CurAmt();
    }

    /**
     * Create an instance of {@link PresSvcRq.BillInqRq.BillerId }
     * 
     */
    public PresSvcRq.BillInqRq.BillerId createPresSvcRqBillInqRqBillerId() {
        return new PresSvcRq.BillInqRq.BillerId();
    }

    /**
     * Create an instance of {@link PaySvcRq.MsgRqHdr.NetworkTrnInfo }
     * 
     */
    public PaySvcRq.MsgRqHdr.NetworkTrnInfo createPaySvcRqMsgRqHdrNetworkTrnInfo() {
        return new PaySvcRq.MsgRqHdr.NetworkTrnInfo();
    }

    /**
     * Create an instance of {@link PaySvcRq.PmtAddRq }
     * 
     */
    public PaySvcRq.PmtAddRq createPaySvcRqMsgRqHdrPmtAddRq() {
        return new PaySvcRq.PmtAddRq();
    }

    /**
     * Create an instance of {@link PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent }
     * 
     */
    public PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent createPaySvcRqMsgRqHdrPointOfServiceDataPOSAgent() {
        return new PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent();
    }

    /**
     * Create an instance of {@link PaySvcRs.PmtAddRs.PmtRec.PmtStatus }
     * 
     */
    public PaySvcRs.PmtAddRs.PmtRec.PmtStatus createPaySvcRsPmtAddRsPmtRecPmtStatus() {
        return new PaySvcRs.PmtAddRs.PmtRec.PmtStatus();
    }

}
