//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
 *         &lt;element name="SPName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PmtAddRs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status" type="{http://example.com/uniws/}statusdata"/>
 *                   &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
 *                   &lt;element name="AsyncRqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
 *                   &lt;element name="PmtRec">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
 *                             &lt;element name="PmtStatus">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="PmtStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="EffDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqUID",
    "spName",
    "pmtAddRs"
})
@XmlRootElement(name = "PaySvcRs")
public class PaySvcRs {

    @XmlElement(name = "RqUID", required = true)
    protected String rqUID;
    @XmlElement(name = "SPName", required = true)
    protected String spName;
    @XmlElement(name = "PmtAddRs", required = true)
    protected PaySvcRs.PmtAddRs pmtAddRs;

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the spName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPName() {
        return spName;
    }

    /**
     * Sets the value of the spName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPName(String value) {
        this.spName = value;
    }

    /**
     * Gets the value of the pmtAddRs property.
     * 
     * @return
     *     possible object is
     *     {@link PaySvcRs.PmtAddRs }
     *     
     */
    public PaySvcRs.PmtAddRs getPmtAddRs() {
        return pmtAddRs;
    }

    /**
     * Sets the value of the pmtAddRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaySvcRs.PmtAddRs }
     *     
     */
    public void setPmtAddRs(PaySvcRs.PmtAddRs value) {
        this.pmtAddRs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status" type="{http://example.com/uniws/}statusdata"/>
     *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
     *         &lt;element name="AsyncRqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
     *         &lt;element name="PmtRec">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
     *                   &lt;element name="PmtStatus">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PmtStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EffDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "rqUID",
        "asyncRqUID",
        "pmtInfo",
        "pmtRec"
    })
    public static class PmtAddRs {

        @XmlElement(name = "Status", required = true)
        protected Statusdata status;
        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "AsyncRqUID", required = true)
        protected String asyncRqUID;
        @XmlElement(name = "PmtInfo", required = true)
        protected PmtData pmtInfo;
        @XmlElement(name = "PmtRec", required = true)
        protected PaySvcRs.PmtAddRs.PmtRec pmtRec;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link Statusdata }
         *     
         */
        public Statusdata getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link Statusdata }
         *     
         */
        public void setStatus(Statusdata value) {
            this.status = value;
        }

        /**
         * Gets the value of the rqUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the asyncRqUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAsyncRqUID() {
            return asyncRqUID;
        }

        /**
         * Sets the value of the asyncRqUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAsyncRqUID(String value) {
            this.asyncRqUID = value;
        }

        /**
         * Gets the value of the pmtInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PmtData }
         *     
         */
        public PmtData getPmtInfo() {
            return pmtInfo;
        }

        /**
         * Sets the value of the pmtInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PmtData }
         *     
         */
        public void setPmtInfo(PmtData value) {
            this.pmtInfo = value;
        }

        /**
         * Gets the value of the pmtRec property.
         * 
         * @return
         *     possible object is
         *     {@link PaySvcRs.PmtAddRs.PmtRec }
         *     
         */
        public PaySvcRs.PmtAddRs.PmtRec getPmtRec() {
            return pmtRec;
        }

        /**
         * Sets the value of the pmtRec property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaySvcRs.PmtAddRs.PmtRec }
         *     
         */
        public void setPmtRec(PaySvcRs.PmtAddRs.PmtRec value) {
            this.pmtRec = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
         *         &lt;element name="PmtStatus">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PmtStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EffDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pmtId",
            "pmtInfo",
            "pmtStatus"
        })
        public static class PmtRec {

            @XmlElement(name = "PmtId", required = true)
            protected String pmtId;
            @XmlElement(name = "PmtInfo", required = true)
            protected PmtData pmtInfo;
            @XmlElement(name = "PmtStatus", required = true)
            protected PaySvcRs.PmtAddRs.PmtRec.PmtStatus pmtStatus;

            /**
             * Gets the value of the pmtId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPmtId() {
                return pmtId;
            }

            /**
             * Sets the value of the pmtId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPmtId(String value) {
                this.pmtId = value;
            }

            /**
             * Gets the value of the pmtInfo property.
             * 
             * @return
             *     possible object is
             *     {@link PmtData }
             *     
             */
            public PmtData getPmtInfo() {
                return pmtInfo;
            }

            /**
             * Sets the value of the pmtInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link PmtData }
             *     
             */
            public void setPmtInfo(PmtData value) {
                this.pmtInfo = value;
            }

            /**
             * Gets the value of the pmtStatus property.
             * 
             * @return
             *     possible object is
             *     {@link PaySvcRs.PmtAddRs.PmtRec.PmtStatus }
             *     
             */
            public PaySvcRs.PmtAddRs.PmtRec.PmtStatus getPmtStatus() {
                return pmtStatus;
            }

            /**
             * Sets the value of the pmtStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link PaySvcRs.PmtAddRs.PmtRec.PmtStatus }
             *     
             */
            public void setPmtStatus(PaySvcRs.PmtAddRs.PmtRec.PmtStatus value) {
                this.pmtStatus = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PmtStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EffDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pmtStatusCode",
                "effDt"
            })
            public static class PmtStatus {

                @XmlElement(name = "PmtStatusCode", required = true)
                protected String pmtStatusCode;
                @XmlElement(name = "EffDt", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar effDt;

                /**
                 * Gets the value of the pmtStatusCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getPmtStatusCode() {
                    return pmtStatusCode;
                }

                /**
                 * Sets the value of the pmtStatusCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setPmtStatusCode(String value) {
                    this.pmtStatusCode = value;
                }

                /**
                 * Gets the value of the effDt property.
                 *
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public XMLGregorianCalendar getEffDt() {
                    return effDt;
                }

                /**
                 * Sets the value of the effDt property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *
                 */
                public void setEffDt(XMLGregorianCalendar value) {
                    this.effDt = value;
                }

            }

        }

    }

}
