//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 *
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqUID",
    "msgRqHdr",
    "spName",
    "pmtAddRq"
})
@XmlRootElement(name = "PaySvcRq")
public class PaySvcRq {

    @XmlElement(name = "RqUID", required = true)
    protected String rqUID;
    @XmlElement(name = "MsgRqHdr", required = true)
    protected PaySvcRq.MsgRqHdr msgRqHdr;
    @XmlElement(name = "SPName", required = true)
    protected String spName;
    @XmlElement(name = "PmtAddRq", required = true)
    protected PaySvcRq.PmtAddRq pmtAddRq;

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the msgRqHdr property.
     * 
     * @return
     *     possible object is
     *     {@link PaySvcRq.MsgRqHdr }
     *     
     */
    public PaySvcRq.MsgRqHdr getMsgRqHdr() {
        return msgRqHdr;
    }

    /**
     * Sets the value of the msgRqHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaySvcRq.MsgRqHdr }
     *     
     */
    public void setMsgRqHdr(PaySvcRq.MsgRqHdr value) {
        this.msgRqHdr = value;
    }

    /**
     * Gets the value of the spName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSPName() {
        return spName;
    }

    /**
     * Sets the value of the spName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSPName(String value) {
        this.spName = value;
    }

    /**
     * Gets the value of the pmtAddRq property.
     *
     * @return
     *     possible object is
     *     {@link PaySvcRq.PmtAddRq }
     *
     */
    public PaySvcRq.PmtAddRq getPmtAddRq() {
        return pmtAddRq;
    }

    /**
     * Sets the value of the pmtAddRq property.
     *
     * @param value
     *     allowed object is
     *     {@link PaySvcRq.PmtAddRq }
     *
     */
    public void setPmtAddRq(PaySvcRq.PmtAddRq value) {
        this.pmtAddRq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NetworkTrnInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NetworkOwner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BankId">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[0-9]{4}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PointOfServiceData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="POSAgent">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AgentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="POSLocation">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[0-9]{5}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SPName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{15}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PmtAddRq">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
     *                   &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "networkTrnInfo",
        "pointOfServiceData"
    })
    public static class MsgRqHdr {

        @XmlElement(name = "NetworkTrnInfo", required = true)
        protected PaySvcRq.MsgRqHdr.NetworkTrnInfo networkTrnInfo;
        @XmlElement(name = "PointOfServiceData", required = true)
        protected PaySvcRq.MsgRqHdr.PointOfServiceData pointOfServiceData;

        /**
         * Gets the value of the networkTrnInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PaySvcRq.MsgRqHdr.NetworkTrnInfo }
         *     
         */
        public PaySvcRq.MsgRqHdr.NetworkTrnInfo getNetworkTrnInfo() {
            return networkTrnInfo;
        }

        /**
         * Sets the value of the networkTrnInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaySvcRq.MsgRqHdr.NetworkTrnInfo }
         *     
         */
        public void setNetworkTrnInfo(PaySvcRq.MsgRqHdr.NetworkTrnInfo value) {
            this.networkTrnInfo = value;
        }

        /**
         * Gets the value of the pointOfServiceData property.
         * 
         * @return
         *     possible object is
         *     {@link PaySvcRq.MsgRqHdr.PointOfServiceData }
         *     
         */
        public PaySvcRq.MsgRqHdr.PointOfServiceData getPointOfServiceData() {
            return pointOfServiceData;
        }

        /**
         * Sets the value of the pointOfServiceData property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaySvcRq.MsgRqHdr.PointOfServiceData }
         *     
         */
        public void setPointOfServiceData(PaySvcRq.MsgRqHdr.PointOfServiceData value) {
            this.pointOfServiceData = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NetworkOwner" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BankId">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[0-9]{4}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "networkOwner",
            "bankId"
        })
        public static class NetworkTrnInfo {

            @XmlElement(name = "NetworkOwner", required = true)
            protected String networkOwner;
            @XmlElement(name = "BankId", required = true)
            protected String bankId;

            /**
             * Gets the value of the networkOwner property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkOwner() {
                return networkOwner;
            }

            /**
             * Sets the value of the networkOwner property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkOwner(String value) {
                this.networkOwner = value;
            }

            /**
             * Gets the value of the bankId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBankId() {
                return bankId;
            }

            /**
             * Sets the value of the bankId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBankId(String value) {
                this.bankId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="POSAgent">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AgentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="POSLocation">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[0-9]{5}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "environment",
            "posAgent",
            "posLocation"
        })
        public static class PointOfServiceData {

            @XmlElement(name = "Environment", required = true)
            protected String environment;
            @XmlElement(name = "POSAgent", required = true)
            protected PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent posAgent;
            @XmlElement(name = "POSLocation", required = true)
            protected String posLocation;

            /**
             * Gets the value of the environment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnvironment() {
                return environment;
            }

            /**
             * Sets the value of the environment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnvironment(String value) {
                this.environment = value;
            }

            /**
             * Gets the value of the posAgent property.
             * 
             * @return
             *     possible object is
             *     {@link PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent }
             *     
             */
            public PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent getPOSAgent() {
                return posAgent;
            }

            /**
             * Sets the value of the posAgent property.
             * 
             * @param value
             *     allowed object is
             *     {@link PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent }
             *     
             */
            public void setPOSAgent(PaySvcRq.MsgRqHdr.PointOfServiceData.POSAgent value) {
                this.posAgent = value;
            }

            /**
             * Gets the value of the posLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOSLocation() {
                return posLocation;
            }

            /**
             * Sets the value of the posLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOSLocation(String value) {
                this.posLocation = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AgentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "agentId"
            })
            public static class POSAgent {

                @XmlElement(name = "AgentId", required = true)
                protected String agentId;

                /**
                 * Gets the value of the agentId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAgentId() {
                    return agentId;
                }

                /**
                 * Sets the value of the agentId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAgentId(String value) {
                    this.agentId = value;
                }

            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
     *         &lt;element name="PmtInfo" type="{http://example.com/uniws/}PmtData"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "rqUID",
            "pmtInfo"
    })
    public static class PmtAddRq {

        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "PmtInfo", required = true)
        protected PmtData pmtInfo;

        /**
         * Gets the value of the rqUID property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the pmtInfo property.
         *
         * @return
         *     possible object is
         *     {@link PmtData }
         *
         */
        public PmtData getPmtInfo() {
            return pmtInfo;
        }

        /**
         * Sets the value of the pmtInfo property.
         *
         * @param value
         *     allowed object is
         *     {@link PmtData }
         *
         */
        public void setPmtInfo(PmtData value) {
            this.pmtInfo = value;
        }

    }
}
