//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PmtData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PmtData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CurAmt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CurCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="E"/>
 *                         &lt;enumeration value="C"/>
 *                         &lt;enumeration value="M"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RemitInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustPayeeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillId" type="{http://example.com/uniws/}UUID-random"/>
 *                   &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CurAmt">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DepAcctIdFrom">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BankInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PrcDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DueDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmtData", propOrder = {
    "curAmt",
    "remitInfo",
    "depAcctIdFrom",
    "prcDt",
    "dueDt"
})
public class PmtData {

    @XmlElement(name = "CurAmt", required = true)
    protected PmtData.CurAmt curAmt;
    @XmlElement(name = "RemitInfo", required = true)
    protected PmtData.RemitInfo remitInfo;
    @XmlElement(name = "DepAcctIdFrom", required = true)
    protected PmtData.DepAcctIdFrom depAcctIdFrom;
    @XmlElement(name = "PrcDt", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prcDt;
    @XmlElement(name = "DueDt", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDt;

    public PmtData(){
        remitInfo = new RemitInfo();
    }

    public PmtData(PmtData copy){
        prcDt = copy.prcDt;
        dueDt = copy.dueDt;
        curAmt = copy.curAmt;
        remitInfo = new RemitInfo();
        remitInfo.curAmt = copy.remitInfo.curAmt;
        remitInfo.billId = copy.remitInfo.billId;
        remitInfo.custPayeeId = copy.remitInfo.custPayeeId;
        remitInfo.pmtId = copy.remitInfo.pmtId;
        depAcctIdFrom = new DepAcctIdFrom();
        depAcctIdFrom.acctId = copy.depAcctIdFrom.acctId;
        depAcctIdFrom.acctType = copy.depAcctIdFrom.acctType;
        depAcctIdFrom.bankInfo = copy.depAcctIdFrom.bankInfo;
    }

    /**
     * Gets the value of the curAmt property.
     * 
     * @return
     *     possible object is
     *     {@link PmtData.CurAmt }
     *     
     */
    public PmtData.CurAmt getCurAmt() {
        return curAmt;
    }

    /**
     * Sets the value of the curAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtData.CurAmt }
     *     
     */
    public void setCurAmt(PmtData.CurAmt value) {
        this.curAmt = value;
    }

    /**
     * Gets the value of the remitInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PmtData.RemitInfo }
     *     
     */
    public PmtData.RemitInfo getRemitInfo() {
        return remitInfo;
    }

    /**
     * Sets the value of the remitInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtData.RemitInfo }
     *     
     */
    public void setRemitInfo(PmtData.RemitInfo value) {
        this.remitInfo = value;
    }

    /**
     * Gets the value of the depAcctIdFrom property.
     * 
     * @return
     *     possible object is
     *     {@link PmtData.DepAcctIdFrom }
     *     
     */
    public PmtData.DepAcctIdFrom getDepAcctIdFrom() {
        return depAcctIdFrom;
    }

    /**
     * Sets the value of the depAcctIdFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtData.DepAcctIdFrom }
     *     
     */
    public void setDepAcctIdFrom(PmtData.DepAcctIdFrom value) {
        this.depAcctIdFrom = value;
    }

    /**
     * Gets the value of the prcDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrcDt() {
        return prcDt;
    }

    /**
     * Sets the value of the prcDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrcDt(XMLGregorianCalendar value) {
        this.prcDt = value;
    }

    /**
     * Gets the value of the dueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDt() {
        return dueDt;
    }

    /**
     * Sets the value of the dueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDt(XMLGregorianCalendar value) {
        this.dueDt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="CurCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="C"/>
     *               &lt;enumeration value="M"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amt",
        "curCode"
    })
    public static class CurAmt {

        @XmlElement(name = "Amt", required = true)
        protected BigDecimal amt;
        @XmlElement(name = "CurCode", required = true)
        protected String curCode;

        /**
         * Gets the value of the amt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmt() {
            return amt;
        }

        /**
         * Sets the value of the amt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmt(BigDecimal value) {
            this.amt = value;
        }

        /**
         * Gets the value of the curCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurCode() {
            return curCode;
        }

        /**
         * Sets the value of the curCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurCode(String value) {
            this.curCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AcctId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AcctType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BankInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "acctId",
        "acctType",
        "bankInfo"
    })
    public static class DepAcctIdFrom {

        @XmlElement(name = "AcctId", required = true)
        protected String acctId;
        @XmlElement(name = "AcctType", required = true)
        protected String acctType;
        @XmlElement(name = "BankInfo", required = true)
        protected String bankInfo;

        /**
         * Gets the value of the acctId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcctId() {
            return acctId;
        }

        /**
         * Sets the value of the acctId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcctId(String value) {
            this.acctId = value;
        }

        /**
         * Gets the value of the acctType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcctType() {
            return acctType;
        }

        /**
         * Sets the value of the acctType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcctType(String value) {
            this.acctType = value;
        }

        /**
         * Gets the value of the bankInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankInfo() {
            return bankInfo;
        }

        /**
         * Sets the value of the bankInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankInfo(String value) {
            this.bankInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustPayeeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillId" type="{http://example.com/uniws/}UUID-random"/>
     *         &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CurAmt">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custPayeeId",
        "billId",
        "pmtId",
        "curAmt"
    })
    public static class RemitInfo {

        @XmlElement(name = "CustPayeeId", required = true)
        protected String custPayeeId;
        @XmlElement(name = "BillId", required = true)
        protected String billId;
        @XmlElement(name = "PmtId", required = true)
        protected String pmtId;
        @XmlElement(name = "CurAmt", required = true)
        protected PmtData.CurAmt curAmt;

        public RemitInfo(){
            curAmt = new CurAmt();
        }

        /**
         * Gets the value of the custPayeeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustPayeeId() {
            return custPayeeId;
        }

        /**
         * Sets the value of the custPayeeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustPayeeId(String value) {
            this.custPayeeId = value;
        }

        /**
         * Gets the value of the billId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillId() {
            return billId;
        }

        /**
         * Sets the value of the billId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillId(String value) {
            this.billId = value;
        }

        /**
         * Gets the value of the pmtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPmtId() {
            return pmtId;
        }

        /**
         * Sets the value of the pmtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPmtId(String value) {
            this.pmtId = value;
        }

        /**
         * Gets the value of the curAmt property.
         * 
         * @return
         *     possible object is
         *     {@link PmtData.CurAmt }
         *     
         */
        public PmtData.CurAmt getCurAmt() {
            return curAmt;
        }

        /**
         * Sets the value of the curAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link PmtData.CurAmt }
         *     
         */
        public void setCurAmt(PmtData.CurAmt value) {
            this.curAmt = value;
        }

    }

}
