//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
 *         &lt;element name="BillInqRs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status" type="{http://example.com/uniws/}statusdata"/>
 *                   &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
 *                   &lt;element name="BillRec" type="{http://example.com/uniws/}billdata"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqUID",
    "billInqRs"
})
@XmlRootElement(name = "PresSvcRs")
public class PresSvcRs {

    @XmlElement(name = "RqUID", required = true)
    protected String rqUID;
    @XmlElement(name = "BillInqRs", required = true)
    protected PresSvcRs.BillInqRs billInqRs;

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the billInqRs property.
     * 
     * @return
     *     possible object is
     *     {@link PresSvcRs.BillInqRs }
     *     
     */
    public PresSvcRs.BillInqRs getBillInqRs() {
        return billInqRs;
    }

    /**
     * Sets the value of the billInqRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresSvcRs.BillInqRs }
     *     
     */
    public void setBillInqRs(PresSvcRs.BillInqRs value) {
        this.billInqRs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status" type="{http://example.com/uniws/}statusdata"/>
     *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
     *         &lt;element name="BillRec" type="{http://example.com/uniws/}billdata"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "rqUID",
        "billRec"
    })
    public static class BillInqRs {

        @XmlElement(name = "Status", required = true)
        protected Statusdata status;
        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "BillRec", required = true)
        protected List<Billdata> billRec;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link Statusdata }
         *     
         */
        public Statusdata getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link Statusdata }
         *     
         */
        public void setStatus(Statusdata value) {
            this.status = value;
        }

        /**
         * Gets the value of the rqUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the billRec property.
         * 
         * @return
         *     possible object is
         *     {@link Billdata }
         *     
         */
        public List<Billdata> getBillRec() {
            if(billRec == null)
                billRec = new ArrayList<>();
            return billRec;
        }

        public void addBillData(Billdata data){
            if(billRec == null)
                billRec = new ArrayList<>();
            billRec.add(data);
        }

    }

}
