//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:21:01 PM COT 
//


package co.edu.unibague.ws.models.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Represents the info send by the bank in any of the search bill methods
 * available.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "rqUID",
        "billInqRq"
})
@XmlRootElement(name = "PresSvcRq")
public class PresSvcRq{

    @XmlElement(name = "RqUID", required = true)
    protected String rqUID;

    @XmlElement(name = "BillInqRq", required = true)
    protected PresSvcRq.BillInqRq billInqRq;

    /**
     * Gets the value of the rqUID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the billInqRq property.
     * 
     * @return
     *     possible object is
     *     {@link PresSvcRq.BillInqRq }
     *     
     */
    public PresSvcRq.BillInqRq getBillInqRq() {
        return billInqRq;
    }

    /**
     * Sets the value of the billInqRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresSvcRq.BillInqRq }
     *     
     */
    public void setBillInqRq(PresSvcRq.BillInqRq value) {
        this.billInqRq = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RqUID" type="{http://example.com/uniws/}UUID-random"/>
     *         &lt;element name="SPName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{15}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="BillerId">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BillerNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "rqUID",
            "spName",
            "billerId",
            "billsId"
    })
    public static class BillInqRq{

        @XmlElement(name = "RqUID", required = true)
        protected String rqUID;
        @XmlElement(name = "SPName", required = true)
        protected String spName;
        @XmlElement(name = "BillerId", required = true)
        protected PresSvcRq.BillInqRq.BillerId billerId;
        @XmlElement(name = "BillId", required = true)
        protected List<String> billsId;

        /**
         * Gets the value of the rqUID property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRqUID() {
            return rqUID;
        }

        /**
         * Sets the value of the rqUID property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRqUID(String value) {
            this.rqUID = value;
        }

        /**
         * Gets the value of the spName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSPName() {
            return spName;
        }

        /**
         * Sets the value of the spName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSPName(String value) {
            this.spName = value;
        }

        /**
         * Gets the value of the billerId property.
         * 
         * @return
         *     possible object is
         *     {@link PresSvcRq.BillInqRq.BillerId }
         *     
         */
        public PresSvcRq.BillInqRq.BillerId getBillerId() {
            return billerId;
        }

        /**
         * Sets the value of the billerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link PresSvcRq.BillInqRq.BillerId }
         *     
         */
        public void setBillerId(PresSvcRq.BillInqRq.BillerId value) {
            this.billerId = value;
        }

        /**
         * Gets the value of the billerId property.
         *
         * @return
         *     possible object is
         *     {@link List<String> }
         *
         */
        public List<String> getBillId() {
            if(billsId == null)
                billsId = new ArrayList<>();
            return billsId;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BillerNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "spName",
            "billerNum"
        })
        public static class BillerId {

            @XmlElement(name = "SPName", required = true)
            protected String spName;
            @XmlElement(name = "BillerNum", required = true)
            protected String billerNum;

            /**
             * Gets the value of the spName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSPName() {
                return spName;
            }

            /**
             * Sets the value of the spName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSPName(String value) {
                this.spName = value;
            }

            /**
             * Gets the value of the billerNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBillerNum() {
                return billerNum;
            }

            /**
             * Sets the value of the billerNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBillerNum(String value) {
                this.billerNum = value;
            }

        }

    }

}
