CREATE TABLE SIA_WS_RECIBO_TEMP(
    CLIENTE NUMBER(16) NOT NULL,
    VALOR      NUMBER NOT NULL,
    FECHA_LIMITE_PAGO DATE NOT NULL,
    REFERENCIA NUMBER(8) PRIMARY KEY,
    REFERENCIA_ACADEMICO VARCHAR2(20),
    TIPO_RECIBO VARCHAR2(8),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE SIA_WS_PAGOS_RIN(
  ID_TRANSACCION  VARCHAR2(36)  NOT NULL,
  ID_BANCO        VARCHAR2(4)   NOT NULL,
  ID_SUCURSAL     VARCHAR2(5)   NOT NULL,
  FECHA_PAGO      DATE          NOT NULL,
  VALOR_PAGO      NUMBER        NOT NULL,
  FORMA_PAGO      CHAR(1)       NOT NULL,
  NIT_PAGADOR     VARCHAR2(15)  NOT NULL,
  ID_FACTURA      VARCHAR2(36)  NOT NULL,
  ID_GRUPO_PAGO   VARCHAR2(14)  NOT NULL,
  CODIGO_ESTADO   NUMBER(1)     DEFAULT 5 NOT NULL,
  FECHA_REGISTRO  DATE          DEFAULT SYSDATE NOT NULL,
  SECUENCIA       NUMBER        PRIMARY KEY,
  CONSTRAINT CHECK_PAYMENT_METHOD_VALUE CHECK(FORMA_PAGO IN ('E', 'C', 'M')),
  CONSTRAINT CHECK_STATUS_VALUE CHECK(CODIGO_ESTADO IN (0, 1, 2, 5, 6))
);

COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_TRANSACCION IS 'RQUID DE LA TRANSACCION';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_BANCO IS 'ID DEL BANCO EN EL QUE SE REALIZA EL PAGO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_SUCURSAL IS 'ID DE LA SUCURSAL EN LA QUE SE REALIZA EL PAGO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_CAJERO IS 'ID DEL CAJERO. VIAJA VACIO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.FECHA_PAGO IS 'FECHA DE REALIZACION DEL PAGO ENVIADA POR EL BANCO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.VALOR_PAGO IS 'CANTIDAD A PAGAR ENVIADA POR EL BANCO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.FORMA_PAGO IS 'METODO DE PAGO (EFECTIVO, CHEQUE, MIXTO)';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.NIT_PAGADOR IS 'NIT DEL TERCERO QUE CANCELA LA FACTURA';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_FACTURA IS 'IDENTIFICADOR DE ICEBERG DE LA FACTURA';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.ID_GRUPO_PAGO IS 'IDENTIFICADOR DE GRUPO ENVIADO POR EL BANCO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.CODIGO_ESTADO IS
'POSIBLE ESTADO DE LA TRANSACCION SEGUN CODIGO DE RESPUESTA DEL BANCO';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.FECHA_REGISTRO IS 'FECHA DE REGISTRO DEL PAGO EN LA TABLA';
COMMENT ON COLUMN SIA_WS_PAGOS_RIN.SECUENCIA IS 'IDENTIFICADOR DE LA TRANSACCION';

--CREATE UNIQUE INDEX SIA_WS_PR_RQUID ON SIA_WS_PAGOS_RIN(
--    (CASE WHEN ESTADO = 'P' THEN ID_TRANSACCION ELSE NULL END));
--CREATE INDEX SIA_WS_PR_BILL_ID_TO_STATUS ON SIA_WS_PAGOS_RIN(ID_FACTURA, ESTADO);
CREATE INDEX SIA_WS_PR_RQUID_TO_STATUS ON SIA_WS_PAGOS_RIN(ID_TRANSACCION, CODIGO_ESTADO);

CREATE SEQUENCE SIA_WS_PR_ID START WITH 100;

CREATE OR REPLACE TRIGGER SIA_WS_PR_ID_AUTO BEFORE INSERT ON SIA_WS_PAGOS_RIN FOR EACH ROW
BEGIN
    SELECT SIA_WS_PR_ID.NEXTVAL INTO :new.SECUENCIA FROM dual;
END;
/

-- Cuidado con los update. Puede generar problemas al modificar un valor pagado y procesado.
-- Trigger desabilitado para pruebas internas
CREATE OR REPLACE TRIGGER SIA_WS_RIN_INSERT_TO_P_ONLINE AFTER INSERT OR UPDATE ON SIA_WS_PAGOS_RIN FOR EACH ROW
WHEN(new.CODIGO_ESTADO = 0)
BEGIN
    INSERT INTO TET_PAGOS_ONLINE(RECIBO_CONSIGNACION, REFERENCIA_VENTA, FECHA_TRANSACCION, FECHA_PAGO, HORA, VALOR,
        NUMERO_TRANSACCION, REFERENCIA_EXTRA1, REFERENCIA_EXTRA2, ESTADO_TRANSACCION, BANCO_PSE, MONEDA, MEDIO_PAGO,
        TIPO_MEDIO_PAGO, ORGANIZACION, PROCESADO) VALUES (:NEW.ID_FACTURA, :NEW.SECUENCIA, :NEW.FECHA_REGISTRO,
        :NEW.FECHA_PAGO, TO_CHAR(:NEW.FECHA_PAGO, 'HH24:MI'), :NEW.VALOR_PAGO, :NEW.SECUENCIA, :NEW.NIT_PAGADOR,
        'WSRIN' || :NEW.ID_GRUPO_PAGO, 10, 'BANCOLOMBIA', 'COP', 37, 8, 1, 'N');
END;
/

CREATE OR REPLACE TYPE SIA_BILL_DATA_TYPE AS OBJECT(
    CLIENTE NUMBER(16),
    VALOR      NUMBER,
    FECHA_LIMITE_PAGO DATE,
    REFERENCIA NUMBER(8),
    REFERENCIA_ACADEMICO VARCHAR2(20),
    TIPO_RECIBO VARCHAR2(8)
);
/

CREATE OR REPLACE TYPE SIA_BILL_ARRAY IS TABLE OF SIA_BILL_DATA_TYPE;
/